# 工作流名称
name: deploy-releases-tagged

# 触发条件
on:
  # 推送事件
  push:
    # 类型为标签创建完成
    tags: 
      - *

env:

# 根据上下文 github.ref $GITHUB_REF
jobs:
  build-project:
    name: build project and upload release
    runs-on: ubuntu-latest

    steps:
      - name: echo env paran
        run: echo $GITHUB_REF
        
      - name: checkout project
        uses: actions/checkout@v2
        with:
          ref: $GITHUB_REF

      - name: setup jdk_1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#      - name: cache maven
#        uses: actions/cache@v1
#        path:
      - name: build project
        run: mvn clean package -U

      - name: create a release
        run: |
          curl  \
            -X POST \
            -H 'Content-Type: application/json' \
            -H 'Content-Type: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{access_token}}' \
            -d '{"tag_name":"worlkflows-$GITHUB_REF","name":"worlkflows-$GITHUB_REF","body":"GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S') version:$GITHUB_REF'sapi","draft":true}' \
            https://api.github.com/repos/XuZhuohao/workflows-study/releases \



      ##-F 'file=./target/*.war;filename=workflows.war' \
