# 工作流名称
name: deploy-releases-tagged

# 触发条件
on:
  # 推送事件
  push:
    # 类型为标签创建完成
    tags: 
      - "*"


# 根据上下文 github.ref $GITHUB_REF
jobs:
  build-project:
    name: build project and upload release
    runs-on: ubuntu-latest

    steps:
      - name: echo env paran
        run: |
          echo $GITHUB_REF
          echo ${{github.ref}}
        
      - name: checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}

      - name: setup jdk_1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#      - name: cache maven
#        uses: actions/cache@v1
#        path:
      - name: build project
        run: mvn clean package -U

      - name: create a release
        run: |
          curl  \
            -X POST \
            -H 'Content-Type: application/json' \
            -H 'Content-Type: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{secrets.ACCESS_TOKEN}}' \
            -d '{"tag_name":"worlkflows-${{github.ref}}","name":"worlkflows-${{github.ref}}","body":"GitHub Actions Auto Builder at $(date +%Y-%m-%d %H:%M:%S) version:${{github.ref}} sapi","draft":"true"}' \
            https://api.github.com/repos/XuZhuohao/workflows-study/releases \
            > result.json
          cat result.json





      ##-F 'file=./target/*.war;filename=workflows.war' \
